replicaCount: 1

image:
  repository: ghcr.io/amine7536/akpe-backend-1
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  host: backend-1.127.0.0.1.nip.io

postgres:
  enabled: true
  host: postgres-postgresql.postgres.svc.cluster.local
  port: 5432
  superuser: postgres
  superuserPassword: postgres
